### PR TITLE
Fix cleanup on exit

### LINKED ISSUE #37: Unable to exit with Ctrl+C (SIGINT)
If running a Jest test suite where DevnetProvider is used (so no explicit spawning of Devnet using devnet-js), it is not possible to exit via Ctrl+C. This is because the default SIGINT handler is overridden and installed when simplify importing from devnet-js.

Basically this ought to be changed:
https://github.com/0xSpaceShard/starknet-devnet-js/blob/9bb8f8eb10f0a91ff549d1d2facb1d4d11e49324/src/devnet.ts#L182

## Proposition

Add a manual process.exit(1) to SIGINT and similar signals/events (perhaps just not to the `exit` handler).

### PR DESCRIPTION
**Pull request by FabijanC**
## Usage related changes

- Close #37

## Checklist:

-   [x] Applied formatting - `npm run format`
-   [x] No linter errors - `npm run lint`
-   [x] Performed code self-review
-   [x] Rebased to the latest commit of the target branch (or merged it into my branch)
    -   Once you make the PR reviewable, please avoid force-pushing
-   [x] Updated the docs if needed
-   [x] Linked the [issues](https://github.com/0xSpaceShard/starknet-devnet-js/issues) resolvable by this PR - [linking info](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
-   [x] Updated the tests if needed; all passing - `npm test`

### CODE REVIEW

File: src/devnet.ts [hunk 1]
```diff
@@ -170,15 +175,27 @@ Alternatively, increase the startup time defined in the config object provided o
...
                 instance.kill();
             }
         }
     }
-}
 
-for (const event of ["exit", "SIGINT", "SIGTERM", "SIGQUIT", "uncaughtException"]) {
-    process.on(event, Devnet.cleanup);
+    private static registerCleanup() {
+        for (const event of ["exit"]) {
```
Comment (tabaktoni) [inline src/devnet.ts:187]: This does not need a for loop
